# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/2i2c-team-compass/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py

# Explicitly opt out of trying to build additional formats such as PDF and ePub
formats: []

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs